version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: workshop_len
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  api:
    build: .
    restart: always
    ports:
      - 8000:8000
      - 9000:9000
    depends_on:
      - db
    
    